project:
  type: website
  output-dir: docs

website:
  title: "Desegpol"
  navbar:
    title: false
    logo: images/Desegpol_logo_transparent.png
    logo-alt: "Desegpol"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: team.qmd
        text: Team
      - href: outputs.qmd
        text: Outputs

format:
  html:
    include-after-body: |
      <div class="footer">
        <p>© 2024 by <a href="https://your-website.com">Your Name</a>. All rights reserved.</p>
      </div>
    include-in-header: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.8.6/css/academicons.min.css">
    theme: cosmo
    css: styles.css
    toc: true

# Link the custom CSS file here
format-html:
  stylesheets: 
    - css/styles.css

editor: visual